class Config:
    def __init__(self): ...

    def with_sensitivity(self, sensitivity: float) -> Config: ...

    def with_control_baseline(self, control_baseline: float) -> Config: ...

    def with_scaling_factors(self, signal: float, control: float) -> Config: ...

    def with_min_raw_signal(self, min_raw_signal: float) -> Config: ...

    def with_pcalling_params(self, min_length: int, merge_within: int, cutoff: float) -> Config: ...
