[package]
name = "biobit-bioproj-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Python bindings for immutable biological-project manifests"
documentation = "TODO"
readme = "README.md"
homepage = "TODO"
repository.workspace = true
license.workspace = true
categories.workspace = true

[lib]
path = "src/bindings/lib.rs"

[dependencies]
biobit-bioproj-rs = { path = "../rs" }
biobit-core-py = { path = "../../../core/py" }
pyo3 = { workspace = true }
