class Segment:
    def __init__(self, start: int, end: int) -> None: ...

    @property
    def start(self) -> int: ...

    @property
    def end(self) -> int: ...

    def len(self) -> int: ...

    def contains(self, pos: int) -> bool: ...

    def intersects(self, other: IntoSegment) -> bool: ...

    def touches(self, other: IntoSegment) -> bool: ...

    def extend(self, left: int = 0, right: int = 0) -> Segment: ...

    def extended(self, left: int = 0, right: int = 0) -> Segment: ...

    def intersection(self, other: IntoSegment) -> Segment | None: ...

    def union(self, other: IntoSegment) -> Segment | None: ...

    @staticmethod
    def merge(segments: list[IntoSegment] | tuple[IntoSegment, ...]) -> list[Segment] | None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __hash__(self) -> int: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __lt__(self, other: object) -> bool: ...

    def __le__(self, other: object) -> bool: ...

    def __gt__(self, other: object) -> bool: ...

    def __ge__(self, other: object) -> bool: ...


IntoSegment = Segment | tuple[int, int]
