class Strandedness:
    Forward = ...
    Reverse = ...
    Unstranded = ...


class MatesOrientation:
    Inward = ...
    Outward = ...
    Matching = ...


class SeqLib:
    class Single(SeqLib):
        strandedness: Strandedness

        def __init__(self, strandedness: Strandedness) -> None: ...

    class Paired(SeqLib):
        strandedness: Strandedness
        orientation: MatesOrientation

        def __init__(self, strandedness: Strandedness, orientation: MatesOrientation) -> None: ...
