class Segment:
    def __init__(self, start: int, end: int) -> None: ...

    def start(self) -> int: ...

    def end(self) -> int: ...

    def len(self) -> int: ...

    def contains(self, pos: int) -> bool: ...

    def intersects(self, other: Segment) -> bool: ...

    def touches(self, other: Segment) -> bool: ...

    def extend(self, left: int = 0, right: int = 0) -> None: ...

    def extended(self, left: int = 0, right: int = 0) -> Segment: ...

    def intersection(self, other: Segment) -> Segment | None: ...

    def union(self, other: Segment) -> Segment | None: ...

    def __str__(self) -> str: ...

    def __hash__(self) -> int: ...
