class RNAPileup:
    def __init__(self) -> None: ...

    def set_sensitivity(self, sensitivity: float) -> RNAPileup: ...

    def set_control_baseline(self, control_baseline: float) -> RNAPileup: ...

    def set_min_signal(self, min_signal: float) -> RNAPileup: ...
