#name: "Rust & Python CI checks"
#
#on:
#  push:
#    branches:
#      - main
#      - dev
#    tags:
#      - '*'
#  pull_request:
#    branches:
#      - main
#      - dev
#
#jobs:
#  rust:
#    name: Rust CI
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup the repository
#        uses: actions/checkout@v4
#      - name: Setup the toolchain
#        uses: dtolnay/rust-toolchain@stable
#      - name: Rust format check
#        run: |
#          rustup component add rustfmt
#          cargo fmt --all -- --check
#      - name: Rust cargo check
#        run: cargo check
#      - name: Rust clippy
#        run: |
#          rustup component add clippy
#          cargo clippy
#      - name: Run rust tests
#        run: cargo test --all-features
#  python:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        target: [ x86_64 ]
#        python-version: [ "3.11", "3.12" ]
#    needs: [ rust ]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Python code style & linting
#        uses: chartboost/ruff-action@v1
#        with:
#          src: "./modules/py/python"
#          version: 0.2.1
#          args: "check"
#      - name: Install dependencies
#        run: |
#          # Install the package and all the relevant dependencies
#          python -m pip install './modules/py[dev]'
#      - name: Mypy type checks
#        run: |
#          mypy --config-file modules/py/pyproject.toml modules/py/python
#      - name: Tests
#        run: |
#          pytest modules/py
