name: Rust & Python CI checks
on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  rust:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup the repository
        uses: actions/checkout@v4
      - name: Setup the environment
        uses: prefix-dev/setup-pixi@v0.8.2
        with:
          pixi-version: 0.41.3
          environments: "rust"
          cache: false
          activate-environment: true
      - name: Rust format check
        run: cargo fmt --all -- --check
      - name: Rust cargo check
        run: cargo check
      - name: Rust clippy
        run: cargo clippy
      - name: Run rust tests
        run: cargo test --all-features
  python:
    name: Python CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64 ]
        python: [ "py-3-13t" ]
    needs: [ rust ]
    steps:
      - name: Setup the environment
        uses: prefix-dev/setup-pixi@v0.8.2
        with:
          pixi-version: 0.41.3
          environments: ${{ matrix.python }}
          cache: false
          activate-environment: true
      - name: Python code style & linting
        run: ruff check
      - name: Build the library
        run: |
          cd biobit/py
          maturin develop
      - name: Mypy type checks
        run: |
          mypy --config-file biobit/py/pyproject.toml biobit/py
      - name: Tests
        run: |
          pytest -x biobit/py
