[package]
name = "biobit-bioproj-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Immutable biological-project manifests"
documentation = "TODO"
readme = "README.md"
homepage = "TODO"
repository.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
derive_more = { workspace = true }
eyre = { workspace = true }
kinded = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
